<?php
// Include Moodle configuration and database setup
ob_start(); // Start output buffering
require_once('../../../config.php'); // Moodle config file for database connection
ob_end_clean(); // Clear any output generated by config.php
require_once($CFG->libdir . '/filelib.php');

global $DB;

// Get the cohortid from the request (POST)
$cohortid = required_param('cohortid', PARAM_INT);

// Ensure the cohort ID is valid and the user has access to it
$cohort = $DB->get_record('cohort', array('id' => $cohortid), '*', MUST_EXIST);

// Fetch the users in the cohort
$sql = "
    SELECT u.id, u.firstname, u.lastname, u.picture
    FROM {user} u
    JOIN {cohort_members} cm ON cm.userid = u.id
    WHERE cm.cohortid = :cohortid
";

$users = $DB->get_records_sql($sql, ['cohortid' => $cohortid]);

// Prepare the response data
$response = [];

foreach ($users as $user) {
    // Get the user picture URL
    $user_picture = new user_picture($user);
    $user_picture->size = 1; // Size for the picture (1 corresponds to the small size)
    $user_picture_url = $user_picture->get_url($PAGE)->out(false);

    // Add the user data to the response array
    $response[] = [
        'id' => $user->id,
        'firstname' => $user->firstname,
        'lastname' => $user->lastname,
        'picture' => $user_picture_url // URL to the user's profile picture
    ];
}


// Return the data as a JSON response
header('Content-Type: application/json');
// Return the response as JSON
echo json_encode($response);