<?php
// Include Moodle config
ob_start(); // Start output buffering
require_once('../../../config.php'); // Moodle config file for database connection
ob_end_clean(); // Clear any output generated by config.php

// Ensure that the request is a POST request
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode(['status' => 'error', 'message' => 'Invalid request method.']);
    exit;
}

// Get the POST parameters
$subsection_id = required_param('subsection_id', PARAM_INT);
$cohort_id = required_param('cohort_id', PARAM_INT);

// Build the SQL query to get all records for the given subsection_id and cohort_id
$sql = "
    SELECT percentage
    FROM {cohorts_topics_completion_data}  -- Replace with the actual table name
    WHERE sectionid = :subsection_id
    AND cohortid = :cohort_id
";

// Execute the query
$records = $DB->get_records_sql($sql, [
    'subsection_id' => $subsection_id,
    'cohort_id' => $cohort_id
]);

// Check if records were found
if ($records) {
    // Return the records' percentages
    $percentages = array_map(function($record) {
        return $record->percentage;
    }, $records);

    echo json_encode(['status' => 'success', 'percentages' => $percentages]);
} else {
    // If no records found, return an empty array
    echo json_encode(['status' => 'success', 'percentages' => []]);
}

exit;
?>