<?php
// Include Moodle configuration and database setup
ob_start(); // Start output buffering
require_once('../../../config.php'); // Moodle config file for database connection
ob_end_clean(); // Clear any output generated by config.php
require_once($CFG->libdir . '/filelib.php');

// Get the POST data
$userid = required_param('userid', PARAM_INT);
$sectionid = required_param('sectionid', PARAM_INT);
$courseid = required_param('courseid', PARAM_INT);
$activityid = required_param('activityid', PARAM_INT);  // Correctly named
$cohortid = required_param('cohortid', PARAM_INT);
$note = required_param('note', PARAM_TEXT);

// Prepare the SQL query to insert the data into the table
$sql = "
    INSERT INTO {session_feedback_notes} (courseid, sectionid, cohortid, userid, activityid, note)
    VALUES (:courseid, :sectionid, :cohortid, :userid, :activityid, :note)
";

// Prepare the query for execution
$params = [
    'courseid' => $courseid,
    'sectionid' => $sectionid,
    'cohortid' => $cohortid,
    'userid' => $userid,
    'activityid' => $activityid,  // Corrected to match the JavaScript parameter
    'note' => $note
];

// Insert the data into the table
try {
    $DB->execute($sql, $params);
    echo json_encode(['status' => 'success', 'message' => 'Data inserted successfully.']);
} catch (Exception $e) {
    echo json_encode(['status' => 'error', 'message' => 'Failed to insert data: ' . $e->getMessage()]);
}
?>