<?php
// require_once('C:/wamp64/www/moodle/config.php');  // Adjust the path as necessary

ob_start(); // Start output buffering
require_once('../../../config.php'); // Moodle config file for database connection
ob_end_clean(); // Clear any output generated by config.php


global $DB;

if (isset($_POST['userid'], $_POST['cohort_id'], $_POST['reason'], $_POST['explanation'] )) {
    $userid = intval($_POST['userid']);
    $courseId = intval($_POST['course_id']);
    $cohortId = intval($_POST['cohort_id']);

    $reason = $_POST['reason'];
    $explanation = $_POST['explanation'];


    // Retrieve the record where user_id matches
    $record = $DB->get_record('popup_alert', ['user_id' => $userid]);

    if ($record && $record->cohortid == $cohortId ) {
        // Update the record
        $record->alert_status = 0; // Update the field
        $record->timestamp = time();  // Update the timestamp
        $record->reason = $reason;
        $record->reason_description = $explanation;


        $DB->update_record('popup_alert', $record);

// Set the response header to indicate JSON output
header('Content-Type: application/json');
        echo json_encode(['status' => 'success', 'message' => 'Record updated successfully.']);
    } else {
        // Set the response header to indicate JSON output
header('Content-Type: application/json');
        echo json_encode(['status' => 'error', 'message' => 'Record not found.']);
    }
} else {
    // Set the response header to indicate JSON output
header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'User ID is missing.']);
}