<?php
// require_once('C:/wamp64/www/moodle/config.php');  // Adjust the path as necessary

ob_start(); // Start output buffering
require_once('../../../config.php'); // Moodle config file for database connection
ob_end_clean(); // Clear any output generated by config.php


global $DB;

if (isset($_POST['userid'], $_POST['selected_topic_id'], $_POST['course_id'], $_POST['completion_percentage'], $_POST['cohort_id'])) {
    $userid = intval($_POST['userid']);
    $selectedTopicId = intval($_POST['selected_topic_id']);
    $courseId = intval($_POST['course_id']);
    $completionPercentage = intval($_POST['completion_percentage']);
    $cohortId = intval($_POST['cohort_id']);
    $userid = intval($_POST['userid']);

    // Retrieve the record where user_id matches
    // $record = $DB->get_record('popup_alert', ['user_id' => $userid, 'cohortid' => $cohortId]);

    $params = ['userid' => $userid, 'cohortid' => $cohortId];

$record = $DB->get_record_sql("
    SELECT *
      FROM {popup_alert}
     WHERE user_id = :userid
       AND cohortid = :cohortid
  ORDER BY timestamp DESC, id DESC
     LIMIT 1
", $params);

    if ($record) {
        // Update the record
        $record->alert_status = 0; // Update the field
        $record->timestamp = time();  // Update the timestamp

        $DB->update_record('popup_alert', $record);

         // Check if a record exists in mdl_cohorts_topics_completion_data
         $existingCompletionData = $DB->get_record('cohorts_topics_completion_data', [
            'courseid' => $courseId,
            'sectionid' => $selectedTopicId,
            'cohortid' => $cohortId
        ]);

       $now = time();

// if ($existingCompletionData) {
//     // Update the existing record
//     $existingCompletionData->status      = ($completionPercentage === 100) ? 'Completed' : 'In Progress';
//     $existingCompletionData->percentage  = $completionPercentage;
//     $existingCompletionData->timemodified = $now; // ✅ update timestamp

//     $DB->update_record('cohorts_topics_completion_data', $existingCompletionData);
//     $message = 'Record updated in cohorts_topics_completion_data.';
// } else {
    // Add a new record
    $newCompletionData = new stdClass();
    $newCompletionData->courseid   = (int)$courseId;
    $newCompletionData->sectionid  = (int)$selectedTopicId;
    $newCompletionData->cohortid   = (int)$cohortId;
    $newCompletionData->status     = ($completionPercentage === 100) ? 'Completed' : 'In Progress';
    $newCompletionData->percentage = (int)$completionPercentage;
    $newCompletionData->timecreated  = $now; // ✅ create timestamp
    $newCompletionData->timemodified = $now; // ✅ initial modified timestamp

    $DB->insert_record('cohorts_topics_completion_data', $newCompletionData);
    $message = 'New record added to cohorts_topics_completion_data.';
// }
// Set the response header to indicate JSON output
header('Content-Type: application/json');
        echo json_encode(['status' => 'success', 'message' => 'Record updated successfully.']);
    } else {
        // Set the response header to indicate JSON output
header('Content-Type: application/json');
        echo json_encode(['status' => 'error', 'message' => 'Record not found.']);
    }
} else {
    // Set the response header to indicate JSON output
header('Content-Type: application/json');
    echo json_encode(['status' => 'error', 'message' => 'User ID is missing.']);
}