<?php
ob_start(); // Start output buffering
require_once('../../config.php'); // Moodle config file for database connection
ob_end_clean(); // Clear any output generated by config.php
require_once($CFG->libdir . '/oauthlib.php');
// courses.php

// Assuming you have Moodle's $DB global available
global $DB;
$sql_courses = "SELECT id, fullname, shortname FROM {course} WHERE id NOT IN (1, 2)";
$courses = $DB->get_records_sql($sql_courses);

// Return the count of courses in JSON format
echo json_encode(['totalLevels' => count($courses)]);
?>