<?php
ob_start(); // Start output buffering
require_once('../../config.php'); // Moodle config file for database connection
ob_end_clean(); // Clear any output generated by config.php

// Use Moodle's $DB global
global $DB;

// Fetch all records from the alert_status_table
$records = $DB->get_records('popup_alert_status', null, '', '*');

// Initialize an array to store user IDs and their corresponding alert statuses
$userStatus = [];

// Loop through each record and extract the user_id and alert_status
foreach ($records as $record) {
    if (isset($record->user_id)) {
        $userStatus[] = [
            'user_id' => $record->user_id,
            'alert_status' => $record->alert_status
        ];
    }
}

// Set the response header to indicate JSON output
header('Content-Type: application/json');

// Return the results in JSON format
echo json_encode(['user_status' => $userStatus]);
?>